import os
import re
import urllib.request
import time
import math

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
PUBLIC_ASSETS_DIR = os.path.join(PROJECT_ROOT, 'public', 'assets')
PUBLIC_CSS_DIR = os.path.join(PUBLIC_ASSETS_DIR, 'css')
PUBLIC_ICONS_DIR = os.path.join(PUBLIC_ASSETS_DIR, 'icons')
PUBLIC_JS_DIR = os.path.join(PUBLIC_ASSETS_DIR, 'js')
ICONS_CSS_PATH = os.path.join(PUBLIC_CSS_DIR, 'icons.css')
SPRITE_SVG_PATH = os.path.join(PUBLIC_ICONS_DIR, 'sprite.svg')


IGNORE_DIRS = {'.git', 'vendor', 'node_modules', 'storage', 'docker', 'scripts'}
TARGET_EXTS = {'.php', '.html', '.js'}

def main():
    for d in [PUBLIC_CSS_DIR, PUBLIC_ICONS_DIR, PUBLIC_JS_DIR]:
        if not os.path.exists(d): os.makedirs(d)

    print("Downloading official material symbols list...")
    url = "https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/MaterialSymbolsRounded%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints"
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    try:
        response = urllib.request.urlopen(req)
        data = response.read().decode('utf-8')
        valid_icons = set([line.split()[0] for line in data.split('\n') if line.strip()])
    except Exception as e:
        print("Failed to download official list:", e)
        return

    print("Scanning project for used icons...")
    word_pattern = re.compile(r'\b([a-z0-9_]+)\b', re.IGNORECASE)
    found_icons = set()

    for root, dirs, files in os.walk(PROJECT_ROOT):
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
        for file in files:
            ext = os.path.splitext(file)[1].lower()
            if ext in TARGET_EXTS:
                filepath = os.path.join(root, file)
                try:
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()
                        words = set(word_pattern.findall(content))
                        found_icons.update(words.intersection(valid_icons))
                except Exception:
                    pass

    print(f"Found {len(found_icons)} icons in the project.")

    print("Downloading SVGs...")
    valid_downloaded = []
    svg_paths = []
    svg_inner_pattern = re.compile(r'<svg[^>]*>(.*?)</svg>', re.IGNORECASE | re.DOTALL)

    for icon in sorted(list(found_icons)):
        url = f"https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded/{icon}/default/24px.svg"
        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            response = urllib.request.urlopen(req)
            svg_data = response.read().decode('utf-8')
            match = svg_inner_pattern.search(svg_data)
            if match:
                valid_downloaded.append(icon)
                svg_paths.append(match.group(1).strip())
        except Exception as e:
            time.sleep(0.1)

    print(f"Successfully downloaded {len(valid_downloaded)} icons.")
    
    COLS = 20
    ROWS = math.ceil(len(valid_downloaded) / COLS)
    if ROWS == 0: ROWS = 1
    
    svg_content = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {COLS * 960} {ROWS * 960}">']
    
    css_content = [
        "/* AUTOGENERATED FILE - DO NOT EDIT DIRECTLY */",
        ".material-symbols-rounded {",
        "  display: inline-block;",
        "  font-size: 24px;",
        "  line-height: 1;",
        "  width: 1em;",
        "  height: 1em;",
        "  background-color: currentColor;",
        "  -webkit-mask-image: url('../icons/sprite.svg');",
        "  mask-image: url('../icons/sprite.svg');",
        f"  -webkit-mask-size: {COLS * 100}% {ROWS * 100}%;",
        f"  mask-size: {COLS * 100}% {ROWS * 100}%;",
        "  -webkit-mask-repeat: no-repeat;",
        "  mask-repeat: no-repeat;",
        "  vertical-align: -0.125em;",
        "  overflow: hidden;",
        "  white-space: nowrap;",
        "  text-indent: 100%;",
        "}"
    ]

    for idx, (icon, path_content) in enumerate(zip(valid_downloaded, svg_paths)):
        col = idx % COLS
        row = idx // COLS
        transform = f"translate({col * 960}, {row * 960 + 960})"
        svg_content.append(f'  <g id="icon-{icon}" transform="{transform}">{path_content}</g>')
        
        x_pos = 0.0 if COLS <= 1 else (col / (COLS - 1)) * 100.0
        y_pos = 0.0 if ROWS <= 1 else (row / (ROWS - 1)) * 100.0
        
        css_content.append(f".msr-{icon} {{")
        css_content.append(f"  -webkit-mask-position: {x_pos:.4f}% {y_pos:.4f}%;")
        css_content.append(f"  mask-position: {x_pos:.4f}% {y_pos:.4f}%;")
        css_content.append("}")

    svg_content.append('</svg>')

    with open(SPRITE_SVG_PATH, 'w', encoding='utf-8') as f:
        f.write("\n".join(svg_content))

    with open(ICONS_CSS_PATH, 'w', encoding='utf-8') as f:
        f.write("\n".join(css_content))
        
    print("Successfully generated sprite.svg and icons.css")

if __name__ == "__main__":
    main()
