import json

translations = {
    "action_success": "Acción exitosa",
    "admin_color_block_desc": "Configura colores sólidos de fondo.",
    "admin_color_block_title": "Color Sólido",
    "admin_manage_subscriptions": "Gestionar Suscripciones",
    "admin_msg_delete_desc": "Elimina el mensaje de manera permanente.",
    "admin_msg_delete_title": "Eliminar Mensaje",
    "admin_not_configured": "No configurado",
    "admin_role_builder": "Constructor de Roles",
    "admin_role_hue_adjust": "Ajuste de Tono",
    "admin_role_hue_adjust_desc": "Ajusta el matiz del color seleccionado.",
    "admin_solid_color_desc": "Color fijo para el rol o suscripción.",
    "admin_solid_color_title": "Color Sólido",
    "admin_stripe_ids_required": "Los IDs de Stripe son obligatorios.",
    "admin_tier_col_level": "Nivel",
    "admin_tier_col_name": "Nombre",
    "admin_tier_col_popularity": "Popularidad",
    "admin_tier_col_visibility": "Visibilidad",
    "admin_tier_color_type": "Tipo de color",
    "admin_tier_color_type_desc": "Elige entre color sólido o gradiente.",
    "admin_tier_delete_desc": "Elimina esta suscripción permanentemente.",
    "admin_tier_delete_title": "Eliminar Suscripción",
    "admin_tier_details_desc": "Configura la información general del nivel.",
    "admin_tier_details_title": "Detalles de Suscripción",
    "admin_tier_edit_title": "Editar Suscripción",
    "admin_tier_empty_desc": "No se encontraron suscripciones.",
    "admin_tier_empty_title": "Sin Suscripciones",
    "admin_tier_feature_required": "Esta característica es requerida.",
    "admin_tier_features_desc": "Configura las características y límites del nivel.",
    "admin_tier_features_title": "Características del Nivel",
    "admin_tier_level_desc": "Nivel jerárquico de esta suscripción (0 para básico).",
    "admin_tier_level_title": "Nivel",
    "admin_tier_limit_canvases": "Lienzos Máximos",
    "admin_tier_limit_canvases_desc": "Cantidad de lienzos personales que puede crear.",
    "admin_tier_limit_members": "Miembros Máximos",
    "admin_tier_limit_members_desc": "Capacidad máxima en sus grupos.",
    "admin_tier_limit_palettes": "Paletas Máximas",
    "admin_tier_limit_palettes_desc": "Cantidad de paletas personalizadas guardadas.",
    "admin_tier_limit_snapshots": "Snapshots",
    "admin_tier_limit_snapshots_desc": "Límite de instantáneas por lienzo.",
    "admin_tier_limit_storage": "Almacenamiento (MB)",
    "admin_tier_limit_storage_desc": "Espacio máximo para recursos del usuario.",
    "admin_tier_limits_desc": "Define los límites técnicos de esta suscripción.",
    "admin_tier_limits_title": "Límites",
    "admin_tier_name": "Nombre de Suscripción",
    "admin_tier_name_level_required": "El nombre y el nivel son obligatorios.",
    "admin_tier_new_title": "Nueva Suscripción",
    "admin_tier_search_empty": "No hay coincidencias en la búsqueda.",
    "admin_tier_search_placeholder": "Buscar suscripción...",
    "admin_tier_status_active": "Activa",
    "admin_tier_status_desc": "Controla si la suscripción está disponible.",
    "admin_tier_status_inactive": "Inactiva",
    "admin_tier_status_popular": "Popular",
    "admin_tier_status_title": "Estado",
    "admin_tier_stripe_monthly": "ID Stripe Mensual",
    "admin_tier_stripe_yearly": "ID Stripe Anual",
    "admin_tiers_title": "Niveles de Suscripción",
    "alt_snapshot": "Instantánea",
    "btn_add_card": "Añadir tarjeta",
    "btn_add_tier": "Añadir nivel",
    "btn_cancel_renew": "Cancelar renovación",
    "btn_connect": "Conectar",
    "btn_disconnect": "Desconectar",
    "btn_logout_all_devices": "Cerrar sesión en todos los dispositivos",
    "btn_set_popular": "Marcar como popular",
    "btn_toggle_visibility": "Alternar visibilidad",
    "cannot_delete_system_tier": "No puedes eliminar el nivel base del sistema.",
    "canvas_personal": "Lienzo Personal",
    "card_deleted_success": "Tarjeta eliminada con éxito.",
    "day_fr_min": "Vi",
    "day_mo_min": "Lu",
    "day_sa_min": "Sá",
    "day_th_min": "Ju",
    "day_tu_min": "Ma",
    "day_we_min": "Mi",
    "delete_card": "Eliminar tarjeta",
    "desc_": "Descripción",
    "desc_delete_payment_method": "Elimina un método de pago guardado.",
    "desc_role_": "Descripción del rol",
    "empty_search_messages": "No se encontraron mensajes.",
    "err_delete_card": "Error al eliminar tarjeta.",
    "err_download_receipt": "Error al descargar recibo.",
    "err_missing_get_id": "Falta el parámetro ID.",
    "err_perk_not_owned": "No posees este beneficio.",
    "err_upgrade_required": "Debes mejorar tu plan para esto.",
    "err_user_not_found": "Usuario no encontrado.",
    "error": "Error",
    "error.user_not_found": "El usuario no ha sido encontrado.",
    "filter_by_sort": "Por orden",
    "filter_sort": "Ordenar",
    "filter_type": "Filtrar por tipo",
    "google_already_linked": "Cuenta de Google ya vinculada.",
    "google_linked_other_user": "Esta cuenta de Google está vinculada a otro usuario.",
    "google_linked_success": "Vinculado con Google exitosamente.",
    "google_not_connected": "Google no está conectado.",
    "google_not_linked": "Tu cuenta de Google no está enlazada.",
    "google_unlinked_success": "Desvinculado con éxito.",
    "lbl_new_value": "Nuevo valor",
    "lbl_prev_value": "Valor anterior",
    "lbl_rejected_plural": "Rechazados",
    "lbl_requires_ultra": "Requiere Ultra",
    "lbl_unknown": "Desconocido",
    "loading_payment_methods": "Cargando métodos de pago...",
    "month_april": "Abril",
    "month_august": "Agosto",
    "month_december": "Diciembre",
    "month_february": "Febrero",
    "month_july": "Julio",
    "month_june": "Junio",
    "month_march": "Marzo",
    "month_november": "Noviembre",
    "month_october": "Octubre",
    "month_short_apr": "Abr",
    "month_short_aug": "Ago",
    "month_short_dec": "Dic",
    "month_short_feb": "Feb",
    "month_short_jul": "Jul",
    "month_short_jun": "Jun",
    "month_short_mar": "Mar",
    "month_short_nov": "Nov",
    "month_short_oct": "Oct",
    "msg_eraser_mode_off": "Modo borrador desactivado.",
    "msg_palette_min_colors": "La paleta debe tener colores mínimos.",
    "msg_palette_name_required": "El nombre de la paleta es requerido.",
    "msg_prot_mode_off": "Modo protección desactivado.",
    "next_billing": "Próxima facturación",
    "none": "Ninguno",
    "perm.": "Permiso ",
    "perm.desc_": "Descripción de permiso ",
    "plan_btn_downgrade": "Bajar de plan",
    "plan_btn_upgrade": "Mejorar plan",
    "plan_desc_": "Descripción de plan",
    "plan_limit_canvases": "Lienzos Personales",
    "plan_limit_canvases_desc": "Crea tus propios lienzos privados.",
    "plan_limit_members": "Miembros por grupo",
    "plan_limit_members_desc": "Invita amigos a trabajar juntos.",
    "plan_limit_snapshots": "Instantáneas (Snapshots)",
    "plan_limit_snapshots_desc": "Guarda el estado completo de tu lienzo.",
    "plan_limit_unlimited": "Ilimitado",
    "protect": "Proteger",
    "role.": "Rol ",
    "role_": "Rol ",
    "sec_logout_all_devices_desc": "Cierra tu sesión activa en cualquier otro equipo.",
    "sec_logout_all_devices_title": "Cerrar sesión global",
    "snapshot_upgrade_plan": "Mejora tu plan para snapshots",
    "status_inactive": "Inactivo",
    "store_content_bomba_racimo_1_desc": "Expande color en gran área.",
    "store_content_lluvia_meteoritos_1_desc": "Impacta varios píxeles de golpe.",
    "subscription_details_desc": "Configuración y precio.",
    "subscription_details_title": "Detalles del Plan",
    "subscription_popular_marked": "Marcado como popular.",
    "table_status": "Estado",
    "tag_": "Etiqueta ",
    "tier_free": "Gratis",
    "title_delete_payment_method": "Eliminar Método de Pago",
    "tooltip_upgrade_plan": "Sube de nivel tu cuenta",
    "unknown_tier": "Suscripción desconocida",
    "upgrade_disclaimer": "Facturado anualmente o mensualmente.",
    "upgrade_monthly_disclaimer": "Se renueva mensualmente.",
    "visibility_updated": "Visibilidad actualizada."
}

def update_json(filepath, data):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = json.load(f)
    except FileNotFoundError:
        content = {}
        
    for k, v in data.items():
        if k in content:
            content[k] = v
            
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(content, f, ensure_ascii=False, indent=4)

admin_file = '/app/translations/es-419/admin.json'
general_file = '/app/translations/es-419/general.json'

update_json(admin_file, translations)
update_json(general_file, translations)
print("Translations updated with Spanish equivalents.")
