FROM python:3.11-slim

RUN apt-get update && apt-get install -y default-mysql-client tzdata && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir cryptography mysql-connector-python redis python-dotenv requests websockets

# Comando por defecto para ejecutar el worker
CMD ["python", "-u", "scripts/worker_backups.py"]