version: '3.8'

services:
  websocket_node:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile.worker
    container_name: rosaura_websocket_node_rust
    restart: always
    networks:
      - rosaura_network
    env_file:
      - .env.ws

networks:
  rosaura_network:
    external: true
    name: projectrosaura_rosaura_network
