
name: spriteboard

services:
  websocket_node:
    image: spriteboard-websocket_node:latest
    build:
      context: .
      dockerfile: docker/rust/Dockerfile.worker
    container_name: spriteboard_websocket_node_rust
    restart: always
    networks:
      - spriteboard_network
    env_file:
      - .env.ws

networks:
  spriteboard_network:
    external: true
    name: spriteboard_network
