<?php

use App\Core\System\PermissionsConstants as PC;

return [
    '/' => ['view' => 'app/home.php'],
    '/explore' => ['view' => 'app/home.php'],

    '/search' => ['view' => 'app/search.php'], 
    '/upgrade' => ['view' => 'app/upgrade.php'], 
    '/premium' => ['view' => 'app/upgrade.php'], 
    '/login' => ['view' => 'auth/login.php', 'guest_only' => true],
    '/login/two-factor' => ['view' => 'auth/login.php', 'guest_only' => true],
    '/register' => ['view' => 'auth/register.php', 'guest_only' => true],
    '/register/aditional-data' => ['view' => 'auth/register.php', 'guest_only' => true],
    '/register/verification-account' => ['view' => 'auth/register.php', 'guest_only' => true],
    '/forgot-password' => ['view' => 'auth/forgot-password.php', 'guest_only' => true],
    '/reset-password' => ['view' => 'auth/reset-password.php', 'guest_only' => true],
    '/account-suspended' => ['view' => 'system/message.php'],
    '/account-deleted' => ['view' => 'system/message.php'],
    '/site-policy/manage-cookies' => ['view' => 'site-policy/manage-cookies.php'],
    '/site-policy' => ['view' => 'site-policy/terms-conditions.php'],
    '/site-policy/terms-conditions' => ['view' => 'site-policy/terms-conditions.php'],
    '/site-policy/privacy-policy' => ['view' => 'site-policy/privacy-policy.php'],
    '/site-policy/cookies-policy' => ['view' => 'site-policy/cookies-policy.php'],
    '/site-policy/legal-notice' => ['view' => 'site-policy/legal-notice.php'],
    '/site-policy/refund-policy' => ['view' => 'site-policy/refund-policy.php'],
    '/settings' => ['view' => 'settings/profile/your-account.php', 'auth' => true],
    '/settings/guest' => ['view' => 'settings/preferences/guest.php', 'guest_only' => true],
    '/settings/your-account' => ['view' => 'settings/profile/your-account.php', 'auth' => true],
    '/settings/security' => ['view' => 'settings/security/security.php', 'auth' => true],
    '/settings/accessibility' => ['view' => 'settings/preferences/accessibility.php', 'auth' => true],
    '/settings/subscription' => ['view' => 'settings/billing/billing.php', 'auth' => true],
    '/settings/billing' => ['view' => 'settings/billing/billing.php', 'auth' => true],
    '/settings/purchase-history' => ['view' => 'settings/billing/purchase-history.php', 'auth' => true],
    '/trash' => ['view' => 'canvases/core/trash.php', 'auth' => true, 'requires_2fa' => false],
    '/canvases/create' => ['view' => 'canvases/core/create.php', 'auth' => true, 'permissions' => [PC::CREATE_CANVAS], 'requires_2fa' => false],
    '/canvases/trash' => ['view' => 'canvases/core/trash.php', 'auth' => true, 'permissions' => [PC::MANAGE_CANVASES], 'requires_2fa' => false],
    '/canvases/manage/requests/:uuid' => ['view' => 'canvases/team/requests.php', 'auth' => true, 'permissions' => [PC::MANAGE_CANVASES], 'requires_2fa' => false],
    '/canvases/edit/:uuid' => ['view' => 'canvases/workspace/edit.php', 'auth' => true, 'permissions' => [PC::MANAGE_CANVASES], 'requires_2fa' => false],
    '/canvases/members/:uuid' => ['view' => 'canvases/team/members.php', 'auth' => true, 'permissions' => [PC::MANAGE_CANVASES], 'requires_2fa' => false],
    '/canvases/manage/invites/:uuid' => ['view' => 'canvases/team/invites.php', 'auth' => true, 'permissions' => [PC::MANAGE_CANVASES], 'requires_2fa' => false],
    '/canvases/manage/roles/:uuid' => ['view' => 'canvases/team/roles.php', 'auth' => true, 'permissions' => [PC::MANAGE_CANVASES], 'requires_2fa' => false],
    '/canvases/manage/role-builder/:uuid' => ['view' => 'canvases/team/role-builder.php', 'auth' => true, 'permissions' => [PC::MANAGE_CANVASES], 'requires_2fa' => false],
    '/canvases/manage/role-builder/:uuid/:role_uuid' => ['view' => 'canvases/team/role-builder.php', 'auth' => true, 'permissions' => [PC::MANAGE_CANVASES], 'requires_2fa' => false],
    '/canvases/manage/role-permissions/:uuid/:role_uuid' => ['view' => 'canvases/team/role-permissions.php', 'auth' => true, 'permissions' => [PC::MANAGE_CANVASES], 'requires_2fa' => false],
    '/canvases/manage/sanctions/:uuid' => ['view' => 'canvases/team/sanctions.php', 'auth' => true, 'permissions' => [PC::MANAGE_CANVASES], 'requires_2fa' => false],
    '/canvases/c/v/:canvas/:msg/:idx' => ['view' => 'canvases/chat/chat-viewer.php', 'auth' => true, 'requires_2fa' => false],
    '/design/:id' => ['view' => 'app/design.php'],
    '/design/s/:uuid' => ['view' => 'canvases/snapshots/snapshots-gallery.php'],
    '/snapshot/view/:id' => ['view' => 'canvases/snapshots/snapshot-viewer.php'],
    '/admin' => ['view' => 'admin/dashboard.php', 'auth' => true, 'permissions' => [PC::ACCESS_ADMIN_PANEL], 'requires_2fa' => false],
    '/admin/dashboard' => ['view' => 'admin/dashboard.php', 'auth' => true, 'permissions' => [PC::ACCESS_ADMIN_PANEL], 'requires_2fa' => false],
    '/admin/subscriptions' => ['view' => 'admin/subscriptions/manage-subscriptions.php', 'auth' => true, 'permissions' => [PC::MANAGE_SUBSCRIPTIONS], 'requires_2fa' => false],
    '/admin/subscription-create' => ['view' => 'admin/subscriptions/subscription-builder.php', 'auth' => true, 'permissions' => [PC::MANAGE_SUBSCRIPTIONS], 'requires_2fa' => false],
    '/admin/subscription-edit/:uuid' => ['view' => 'admin/subscriptions/subscription-builder.php', 'auth' => true, 'permissions' => [PC::MANAGE_SUBSCRIPTIONS], 'requires_2fa' => false],
    '/admin/subscription-color/:uuid' => ['view' => 'admin/subscriptions/subscription-color.php', 'auth' => true, 'permissions' => [PC::MANAGE_SUBSCRIPTIONS], 'requires_2fa' => false],
    '/admin/advertisements' => ['view' => 'admin/advertisements/manage-advertisements.php', 'auth' => true, 'permissions' => [PC::MANAGE_ADVERTISEMENTS], 'requires_2fa' => false],
    '/admin/advertisement-items/:uuid' => ['view' => 'admin/advertisements/manage-ads.php', 'auth' => true, 'permissions' => [PC::MANAGE_ADVERTISEMENTS], 'requires_2fa' => false],

    '/admin/messages' => ['view' => 'admin/messages/manage-messages.php', 'auth' => true, 'permissions' => [PC::MANAGE_CONTENT], 'requires_2fa' => false],
    '/admin/messages/reports/:uuid' => ['view' => 'admin/messages/reports.php', 'auth' => true, 'permissions' => [PC::MANAGE_CONTENT], 'requires_2fa' => false],
    '/admin/users' => ['view' => 'admin/users/manage-users.php', 'auth' => true, 'permissions' => [PC::VIEW_USERS], 'requires_2fa' => false],
    '/admin/user-profile/:uuid' => ['view' => 'admin/users/edit-user.php', 'auth' => true, 'permissions' => [PC::EDIT_USERS], 'requires_2fa' => false],
    '/admin/user-moderation/:uuid' => ['view' => 'admin/users/edit-status.php', 'auth' => true, 'permissions' => [PC::MODERATE_USERS], 'requires_2fa' => false],
    '/admin/user-activity/:uuid' => ['view' => 'admin/users/user-history.php', 'auth' => true, 'permissions' => [PC::VIEW_KARDEX], 'requires_2fa' => false],
    '/admin/roles' => ['view' => 'admin/roles/manage-roles.php', 'auth' => true, 'permissions' => [PC::VIEW_ROLES], 'requires_2fa' => false],
    '/admin/role-permissions/:uuid' => ['view' => 'admin/roles/role-permissions.php', 'auth' => true, 'permissions' => [PC::MANAGE_ROLES_STRUCTURE], 'requires_2fa' => false],
    '/admin/backups' => ['view' => 'admin/backups/backups.php', 'auth' => true, 'permissions' => [PC::CREATE_BACKUPS, PC::RESTORE_BACKUPS], 'requires_2fa' => false],
    '/admin/backup-schedule' => ['view' => 'admin/backups/backups-automation.php', 'auth' => true, 'permissions' => [PC::CREATE_BACKUPS], 'requires_2fa' => false],
    '/admin/backup-create' => ['view' => 'admin/backups/backups-create.php', 'auth' => true, 'permissions' => [PC::CREATE_BACKUPS], 'requires_2fa' => false],
    '/admin/backup-restore/:uuid' => ['view' => 'admin/backups/backups-restore.php', 'auth' => true, 'permissions' => [PC::RESTORE_BACKUPS], 'requires_2fa' => false],
    '/admin/system-settings' => ['view' => 'admin/system/server-config.php', 'auth' => true, 'permissions' => [PC::MANAGE_SERVER_CONFIG], 'requires_2fa' => false],
    '/admin/logs' => ['view' => 'admin/logs/logs.php', 'auth' => true, 'permissions' => [PC::VIEW_LOGS], 'requires_2fa' => false],
    '/admin/logs/viewer' => ['view' => 'admin/logs/logs-viewer.php', 'auth' => true, 'permissions' => [PC::VIEW_LOGS], 'requires_2fa' => false]
];
?>
