<?php

return [
    '/' => ['view' => 'app/home.php'],

    '/search' => ['view' => 'app/search.php'], 
    '/upgrade' => ['view' => 'app/upgrade.php'], 
    '/premium' => ['view' => 'app/upgrade.php'], 
    '/store/coins' => ['view' => 'app/store-coins.php', 'auth' => true],
    '/store/content' => ['view' => 'app/store-content.php', 'auth' => true],
    '/login' => ['view' => 'auth/login.php', 'guest_only' => true],
    '/login/two-factor' => ['view' => 'auth/login.php', 'guest_only' => true],
    '/register' => ['view' => 'auth/register.php', 'guest_only' => true],
    '/register/aditional-data' => ['view' => 'auth/register.php', 'guest_only' => true],
    '/register/verification-account' => ['view' => 'auth/register.php', 'guest_only' => true],
    '/forgot-password' => ['view' => 'auth/forgot-password.php', 'guest_only' => true],
    '/reset-password' => ['view' => 'auth/reset-password.php', 'guest_only' => true],
    '/account-suspended' => ['view' => 'system/message.php'],
    '/account-deleted' => ['view' => 'system/message.php'],
    '/site-policy' => ['view' => 'site-policy/site-policy.php'],
    '/site-policy/terms-conditions' => ['view' => 'site-policy/terms-conditions.php'],
    '/site-policy/privacy-policy' => ['view' => 'site-policy/privacy-policy.php'],
    '/site-policy/cookies-policy' => ['view' => 'site-policy/cookies-policy.php'],
    '/site-policy/legal-notice' => ['view' => 'site-policy/legal-notice.php'],
    '/site-policy/refund-policy' => ['view' => 'site-policy/refund-policy.php'],
    '/settings' => ['view' => 'settings/index.php'],
    '/settings/guest' => ['view' => 'settings/preferences/guest.php', 'guest_only' => true],
    '/settings/your-account' => ['view' => 'settings/profile/your-account.php', 'auth' => true],
    '/settings/security' => ['view' => 'settings/security/security.php', 'auth' => true],
    '/settings/accessibility' => ['view' => 'settings/preferences/accessibility.php', 'auth' => true],
    '/settings/subscription' => ['view' => 'settings/billing/billing.php', 'auth' => true],
    '/settings/billing' => ['view' => 'settings/billing/billing.php', 'auth' => true],
    '/settings/purchase-history' => ['view' => 'settings/billing/purchase-history.php', 'auth' => true],
    '/settings/change-password' => ['view' => 'settings/security/change-password.php', 'auth' => true],
    '/settings/2fa' => ['view' => 'settings/security/2fa.php', 'auth' => true],
    '/settings/2fa/recovery-codes' => ['view' => 'settings/security/2fa-recovery-codes.php', 'auth' => true],
    '/settings/2fa/deactivate' => ['view' => 'settings/security/2fa-deactivate.php', 'auth' => true],
    '/settings/delete-account' => ['view' => 'settings/profile/delete-account.php', 'auth' => true],
    '/canvases/create' => ['view' => 'canvases/core/create.php', 'auth' => true, 'permissions' => ['create_canvas'], 'requires_2fa' => false],
    '/canvases/manage' => ['view' => 'canvases/core/manage.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/manage/requests/:uuid' => ['view' => 'canvases/team/requests.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/manage/resets/:uuid' => ['view' => 'canvases/workspace/reset.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/edit/:uuid' => ['view' => 'canvases/workspace/edit.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/fix-roles' => ['view' => 'system/fix-roles.php', 'auth' => false, 'requires_2fa' => false],
    '/canvases/members/:uuid' => ['view' => 'canvases/team/members.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/members/:uuid/role/:user_uuid' => ['view' => 'canvases/team/change-role.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/manage/resize/:uuid' => ['view' => 'canvases/workspace/resize.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/manage/invites/:uuid' => ['view' => 'canvases/team/invites.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/manage/invites/generate/:uuid' => ['view' => 'canvases/team/invites-generate.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/manage/roles/:uuid' => ['view' => 'canvases/team/roles.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/manage/role-builder/:uuid' => ['view' => 'canvases/team/role-builder.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/manage/role-permissions/:uuid' => ['view' => 'canvases/team/role-permissions.php', 'auth' => true, 'permissions' => ['manage_canvases'], 'requires_2fa' => false],
    '/canvases/manage/chat-restriction/:uuid/:user_uuid' => ['view' => 'canvases/team/chat-restriction.php', 'auth' => true, 'requires_2fa' => false],
    '/canvases/chat-viewer' => ['view' => 'canvases/chat/chat-viewer.php', 'auth' => true, 'requires_2fa' => false],
    '/canvases/join' => ['view' => 'canvases/core/join.php', 'auth' => true, 'permissions' => ['join_canvas'], 'requires_2fa' => false],
    '/canvases/palettes/create' => ['view' => 'canvases/palettes/custom-palette-create.php', 'auth' => true, 'requires_2fa' => false],
    '/design/s/:uuid' => ['view' => 'canvases/snapshots/snapshots-gallery.php'],
    '/snapshot/view/:id' => ['view' => 'canvases/snapshots/snapshot-viewer.php'],
    '/admin' => ['view' => 'admin/dashboard.php', 'auth' => true, 'permissions' => [\App\Core\System\PermissionsConstants::ACCESS_ADMIN_PANEL], 'requires_2fa' => false],
    '/admin/dashboard' => ['view' => 'admin/dashboard.php', 'auth' => true, 'permissions' => [\App\Core\System\PermissionsConstants::ACCESS_ADMIN_PANEL], 'requires_2fa' => false],
    '/admin/messages' => ['view' => 'admin/messages/manage-messages.php', 'auth' => true, 'permissions' => ['view_logs'], 'requires_2fa' => false],
    '/admin/messages/visibility/:uuid' => ['view' => 'admin/messages/edit-visibility.php', 'auth' => true, 'permissions' => ['view_logs'], 'requires_2fa' => false],
    '/admin/messages/reports/:uuid' => ['view' => 'admin/messages/reports.php', 'auth' => true, 'permissions' => ['view_logs'], 'requires_2fa' => false],
    '/admin/manage-users' => ['view' => 'admin/users/manage-users.php', 'auth' => true, 'permissions' => ['view_users'], 'requires_2fa' => false],
    '/admin/edit-user/:uuid' => ['view' => 'admin/users/edit-user.php', 'auth' => true, 'permissions' => ['edit_users'], 'requires_2fa' => false],
    '/admin/edit-status/:uuid' => ['view' => 'admin/users/edit-status.php', 'auth' => true, 'permissions' => ['moderate_users'], 'requires_2fa' => false],
    '/admin/user-history/:uuid' => ['view' => 'admin/users/user-history.php', 'auth' => true, 'permissions' => ['view_kardex'], 'requires_2fa' => false],
    '/admin/edit-user-role/:uuid' => ['view' => 'admin/users/edit-user-role.php', 'auth' => true, 'permissions' => [\App\Core\System\PermissionsConstants::ASSIGN_ROLES], 'requires_2fa' => false],
    '/admin/manage-roles' => ['view' => 'admin/roles/manage-roles.php', 'auth' => true, 'permissions' => [\App\Core\System\PermissionsConstants::VIEW_ROLES], 'requires_2fa' => false],
    '/admin/roles/create' => ['view' => 'admin/roles/role-builder.php', 'auth' => true, 'permissions' => [\App\Core\System\PermissionsConstants::MANAGE_ROLES_STRUCTURE], 'requires_2fa' => false],
    '/admin/roles/edit/:uuid' => ['view' => 'admin/roles/role-builder.php', 'auth' => true, 'permissions' => [\App\Core\System\PermissionsConstants::MANAGE_ROLES_STRUCTURE], 'requires_2fa' => false],
    '/admin/roles/permissions/:uuid' => ['view' => 'admin/roles/role-permissions.php', 'auth' => true, 'permissions' => [\App\Core\System\PermissionsConstants::MANAGE_ROLES_STRUCTURE], 'requires_2fa' => false],
    '/admin/backups' => ['view' => 'admin/backups/backups.php', 'auth' => true, 'permissions' => ['create_backups', 'restore_backups'], 'requires_2fa' => false],
    '/admin/backups/automation' => ['view' => 'admin/backups/backups-automation.php', 'auth' => true, 'permissions' => ['create_backups'], 'requires_2fa' => false],
    '/admin/backups/create' => ['view' => 'admin/backups/backups-create.php', 'auth' => true, 'permissions' => ['create_backups'], 'requires_2fa' => false],
    '/admin/backups/restore/:uuid' => ['view' => 'admin/backups/backups-restore.php', 'auth' => true, 'permissions' => ['restore_backups'], 'requires_2fa' => false],
    '/admin/server-config' => ['view' => 'admin/system/server-config.php', 'auth' => true, 'permissions' => ['manage_server_config'], 'requires_2fa' => false],
    '/admin/logs' => ['view' => 'admin/logs/logs.php', 'auth' => true, 'permissions' => ['view_logs'], 'requires_2fa' => false],
    '/admin/logs/viewer' => ['view' => 'admin/logs/logs-viewer.php', 'auth' => true, 'permissions' => ['view_logs'], 'requires_2fa' => false]
];
?>