services:
  lb:
    image: nginx:alpine
    container_name: rosaura_load_balancer
    ports:
      - "80:80"
      - "443:443"
      - "8765:8765"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      - rosaura_lb_network

networks:
  rosaura_lb_network:
    driver: bridge
