version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    container_name: rosaura_app
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
    env_file:
      - ../.env
    environment:
      - TZ=${APP_TIMEZONE:-UTC}
      # Estas variables deben apuntar a la IP PRIVADA del VPS 4
      - DB_HOST=${DB_HOST_PROD} 
      - REDIS_HOST=${REDIS_HOST_PROD}
      - TYPESENSE_HOST=${TYPESENSE_HOST_PROD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT_PROD}
      - SESSION_DRIVER=redis
    networks:
      - rosaura_app_network

networks:
  rosaura_app_network:
    driver: bridge
