events {
    worker_connections 1024;
}

http {
    upstream backend_app {
        # Aquí añades las IPs privadas de tus App Nodes (VPS 2, VPS 3, etc.)
        server 192.168.x.2:80;
        # server 192.168.x.3:80; 
        # server 192.168.x.4:80;
    }

    server {
        listen 80;
        
        # En el futuro, aquí puedes configurar los certificados SSL (Let's Encrypt)
        # y redirigir el tráfico del puerto 80 al 443.

        location / {
            proxy_pass http://backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # location /ws {
        #     proxy_pass http://192.168.x.5:8765;
        #     proxy_http_version 1.1;
        #     proxy_set_header Upgrade $http_upgrade;
        #     proxy_set_header Connection "Upgrade";
        # }
    }
}
